### ISSUE TITLE
Platforms configuration needs to allow different role names per account

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestAgent#10]
Currently, we use the follow model which assumes that all accounts will use the same role name. This is not always the case.

### Old
```yaml
platforms:
  aws:
    accounts:
      - 000000000001
      - 000000000002
    role_name: my_role
```

### New
```yaml
platforms:
  aws:
    accounts:
      - id: 000000000001        # now as list of dict
        role: account-one-role  # specify role here
      - id: 000000000002
        role: account-two-role
    default_account: readonly   # a default role will make it easier when an org uses the same role name for every account
```
