### ISSUE TITLE
Redis Task Standardization Effort

### ISSUE THREAD

**Issue by fiona-june-leathers** [Cloud-Harvest/CloudHarvestAgent#8]
### Summary 
Currently, there are three different silos responsible for recording my job/task chain statuses. Their formats and implementations also differ. To resolve this, we will consolidate all formats into one and bring the tasks into the same database, regardless of status.

This will drastically simplify reporting and status checks.

We will also use the name/key/value Redis model instead of the name/JSON value model currently in use. This will reduce overhead when retrieving or updating specific data points.

### New record format
```yaml
redis_name:  #task:<parent>:<id> or task::<id>
  id: uuid
  parent: uuid of the request which created this task with multiple other tasks
  name: task chain name
  type: report vs harvest (based on top level temple key)
  status: chain status code
  agent: binding up and port number
  position: current task # in chain
  total: total known tasks in chain (this can change based on iterators)
  start: when the chain began
  end: when the chain finished
  result: the result of the chain, including metadata
```

Other keys may be included but at this junction, those are the most salient.

### Affected reports
We will also update the corresponding `harvest.jobs` template report to simplify it, thereby reducing future maintenance toil for that report.

#### CloudHarvestCoreTasks.BaseTaskChain
Need a new argument, `parent`, which is an optional string representation of a uuid4.

Requires update as it is responsible for pushing results to the destination silo.

#### CloudHarvestAgent.JobQueue
Status reporting will need to use the `task:<parent>:<id>` or `task::<id>` convention instead of the current model.
